### ISSUE TITLE
Future Directions for Library Carpentry - Opening a Discussion

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/librarycarpentry#48] opened 2017-07-09 06:34 UTC
Two sprints in, and with a growing community worldwide, I think it is time to think about our **future direction**.

In order to grow, and to meet the needs of new people who want to get involved, we need some mechanisms in place to handle enquiries and deal with requests for workshops - and possibly - engage with funders. We also need some ground rules about what kind of community we are, how we skill up our people, what we teach, and how we conduct ourselves.

To some extent, we have piggybacked on the Carpentries up till now - adapting some of their material, getting a cohort of librarians trained as instructors through their training program, following their code of conduct, and using infrastructure like workshop templates to advertise workshops or their AMY system to record them.

But we cannot and should not do this indefinitely - we would be like twenty-somethings still living in our parents’ home - using the family car, hogging the wifi - but not necessarily contributing back. 

So the time has come to take stock and think about whether we aim to become a full-fledged 'Carpentry' or whether we go off in some other direction.

In my opinion, the status quo cannot hold. It worked for us between the 2016 sprint and now, but the massive explosion of interest since 2016, the quintupling of involvement between the 2016 and 2017 sprints, and the growth of new communities eager to teach the skills means we need something more. 

There is a lot to manage. Already I am overwhelmed by the workload of handling enquiries, requests to teach, and so on. It may not be quite so much work for other people but it has become completely untenable for me: demand in the southern hemisphere is seemingly bottomless. I have just posted **eight** more workshops and am juggling requests for another five or six – when I already have a very busy day job!

But equally there are library and archivist organisations out there who want to get on board so we need to have some kind of official structure they can engage with and possibly fund. Money - lots of money - to spread these skills could be potentially on the table in the US, Canada, the Netherlands - it is already being provided in Australia, New Zealand and South Africa. That kind of interest and demand needs to be managed.

What I do in managing and teaching workshops, time-consuming as it is, is probably inefficient - wrangling via email is a silly way to work - things can so easily fall through the cracks, and one person teaching doesn't scale. 

The systems Software and Data Carpentry have in place - which some people have tagged as bureaucratic or unacceptable overhead - are actually enablers: there are **clear pathways** to request workshops, to request instructor training, to debrief after a workshop or get guidance before. These systems actually facilitate involvement, whereas our *ad hoc* structure does not. 

Because we don't have structure, it doesn't mean we don't have 'overhead' – we do, but it is largely hidden. I know because I handle a huge swathe of it (as do others).

I for one cannot continue to do so in an *ad hoc* way. 

So do we join with Software and Data Carpentry or strike out on our own? Software and Data Carpentry have already decided two systems are untenable and are [planning to merge into one organisation](https://software-carpentry.org/blog/2017/06/merger.html). I don't think we should build our own instructor training system, our own workshop systems, when such proven systems already exist.

We need a structure and a system of governance that assigns responsibilities but that also opens up pathways for people to play a role. *Ad hoc* structures - what we have now - don't allow people to do that. They are actual barriers because no--one is sure who is authorised to do what or how they might take the initiative.

At the very least we need to decide:

- Who is a Library Carpentry instructor?
- What do we teach? Do we mandate a core, or let people pick and mix?
- What is a Library Carpentry workshop, and what is a local adaptation? And is that fine? Or not?
- How do we train new people in our teaching and workshop methods?
- How do we accurately record all the workshops we teach and provide a mechanism for people to do that themselves?
- How do we create local structures people can join, e.g. local chapters?

I would suggest we need at least some kind of interim Steering Committee to manage discussion about these areas. Having advisors from the library and archives world would also be great. 

Who is on a committee, how it would work - these issues can all be discussed openly.

This document aims to open that discussion. This initiative arises out of a community call last Friday night, notes of which can be found [here](http://pad.software-carpentry.org/post-lc2017).

We did have a couple of discussion threads [here](https://github.com/data-lessons/librarycarpentry/issues/7) and [here](https://github.com/data-lessons/librarycarpentry/issues/6) about all this after the success of the 2016 sprint. People should go back to those and read through the issues raised, but I thought it was important to start a new thread in case new people prefer to come to these issues anew.

Please have your say! Building Library Carpentry has been a strong community effort. We would like its future direction to be decided by its community. 

Over to you.

**Comment by Repositorian** [comment] 2017-07-09 07:26
Having a clear scope for Library Carpentry seems super important to achieving community consensus and coherence. Q: Right now LC appears to be focused on coding and software skills for librarians to perform library operational tasks? 

The reason the scoping seems important at this early stage is to help folks in the library community navigate possibilities and find their own way. Many of us in libraries are advancing a skill set comparable to LC but are more out of the library facing:  for example, those of us in scholarly  communication and research impact jobs are highly engaged in developing and teaching nonlibrarians to munge scholarly metadata; write and publish openly; demonstrate research impact; apply semantic web and linked open data to establish research networks and communicate research findings more openly and in machine-reuseable forms.  Thus the speciation into AuthorCarpentry, rather than LC. 

Clearly there are many points of intersection among various "librarian carpentry" approaches: having a clear scope for capital LC would be very helpful to better understanding how our respective efforts can add strength to strength and find a sustainable growth path in support of the many learners we strive to empower!

**Comment by drjwbaker** [comment] 2017-07-09 08:48
Thanks Belinda. I'll have a proper read/think tomorrow.

**Comment by jezcope** [comment] 2017-07-09 10:54
Thanks Belinda, great conversation starter! I might put one or more position-paper-type posts on https://erambler.co.uk/ to avoid packing too much long-winded content into this thread.

**Comment by jezcope** [comment] 2017-07-09 11:01
Initial thoughts:

* We should integrate and collaborate with SWC/DC as much as possible.
* The existing instructor training is focused on pedagogy and not specific content, so is already fit for purpose.
* The key difference, both for our content and the instructors teaching it, is that the assumptions about prior knowledge/experience of LC learners are very different to those for SWC/DC learners — perhaps a more general way of thinking about the LC material is "SWC/DC Essentials", the stuff you would need to learn if you weren't ready for a standard SWC/DC workshop?

**Comment by gvwilson** [comment] 2017-07-09 12:00
I'm obviously biased toward the Carpentries, but setting that aside, I think that being part of a larger effort has many more benefits than drawbacks.  Instructor training and workshop management infrastructure have taken years to develop, and are expensive to keep going; duplicating them will only sap resources that could be used more effectively elsewhere.  Equally, a community that can *and will* create and deliver training doesn't have to be built from scratch.

Two questions I'd want answered going forward are:

1. How are various Carpentries represented in the governance of a united organization?  SWC and DC are currently discussing details of a merger; now would be the right time for LC to chime in, both in its own right and as an exemplar of how other specializations might be given a fair voice in decision making in future.

2. Is LC going to target *all* librarians, or *research* librarians?  The former need our help, but have a much more diverse set of needs; the latter group is smaller, but more focused and has more homogeneous needs.  My instinct is to focus on research librarians for the next couple of years and then re-evaluate.

Finally, may I suggest that we agree in advance *how* the decision will be made?  I propose "of, by, and for the people": whatever proposal is formulated should be put to a vote, and everyone who has contributed to an LC lesson and/or taught an LC workshop constitute the electorate.

**Comment by drjwbaker** [comment] 2017-07-10 07:45
We should merge into The Carpentries.

If they'll have us, we should do this in such a way that:

- Retains the MO/mission of SWC/DC.
- Recognises the attractiveness - as @ostephens has said many times - of the word 'Library' to librarians.
- Recognises - as @jezcope writes https://github.com/data-lessons/librarycarpentry/issues/48#issuecomment-313913132 - 'that the assumptions about prior knowledge/experience of LC learners are very different to those for SWC/DC learners'.
- Focuses on library practice, with a nod - per @gvwilson - to the work of research librarians but with a view to reviewing that focus later.

In the interim:

- We need to have better systems for fielding queries about new workshops.
- We need to do fewer workshops. Or, put another way, accept that we cannot and should not scale any further without first getting our house in order: given that are entirely voluntary, I don't think we should feel obliged to put on a workshop just because someone asks.

**Comment by jt14den** [comment] 2017-07-10 13:09
Thanks @weaverbel for kicking this off.  I agree we need to develop some LC governance and can't continue relying on the scaffolding that Data & Software Carpentry has generously provided. I   support merging with the carpentries and creating an interim steering committee to do that, but agree with @gvwilson that we should put it to a vote of LC lesson contributors and active workshop instructors.

For me, sharing the workshop and instructor training infrastructure and workflows will be crucial to helping bring clarity to planning, managing and being able to pull off more LC workshops. Data & Software Carpentry has a proven open education model that scales and we should join forces.

Some further important benefits include:

* Lesson development and templating. We are currently using the Carpentry lesson template and benefit from the lesson structure that is well conceived and documented.  We want to continue to benefit and contribute to improvements.
* Online meeting/communication structure. Plugging into the instructor, trainer and mentor calls will help us improve our teaching practice and lesson materials over time.
     * This is a two-way thing and gives us ways to improve the Carpentries. We have a lot to contribute to the Carpentries (E.g. our positive experiences with Gitter for communication and MozSprints for lesson collaboration).  
* A community structure members can engage and evolve through. People will come into the community as newbies, grow, learn, teach and contribute and then poss. leave as circumstances and job roles change.
     * The Carpentries provide a big-tent for Library Carpentry to live in: we can have Library Carpentry  governance and contributing roles that are specific to us and Carpentry level governance and community roles that contribute to the common good of the whole community.
     * For example, there are many librarians with educational & assessment training and backgrounds who could help develop and improve the Carpentry-wide instructor training and assessment carpentry activities.

I also appreciate @gvwilson's instinct that we consider focusing on research libraries.  I think we are def. in a similar situation to that of researchers with no CS background having to learn software and data skills to do research. However, ours is also at the organizational level: research libraries, who support research and teaching missions of universities, are having to respond to the changes in research needs. Librarians with no coding or data backgrounds are dropped into an environment where they are asked to support a research lifecycle that is very different than what we were expected to support 10 years ago. Digital libraries, archives, and metadata services in libraries are also asked to be research partners in digital scholarship and data science projects, but also often do not have software and data background. Teaching library carpentry and endeavoring to fill out a curriculum that addresses these skills-gaps in a scalable community-of-practice model could really help librarians in the trenches dealing with these issues.

**Comment by pitviper6** [comment] 2017-07-10 13:12
Another vote for merging with SWC/DC, and collaborating/sharing with them wherever it makes sense.

Library Carpentry has a ton of momentum right now, especially after the wildly successful sprint. The challenge is how to turn that momentum into a steady growth, to continue building a strong community, and continue to develop quality training for instructors and top-notch lessons/materials.

One of the the most time-and-resource consuming aspects of a movement like this is maintenance of workflow and infrastructure. LC is international in scope, and thus we've got wildly different time zones, backgrounds, talents and interests - there needs to be people charged with the bigger picture, so that the same lesson isn't developed by different people working at cross purposes, that there are easily found answers to questions, and that we are able to support those who want to hold workshops but don't have experience in doing so.

Library Carpentry is made up of volunteers. SWC/DC have a great track record in retaining their lesson developers and instructors and we should use their expertise in doing so. The last thing you want to do is frustrate an enthusiastic volunteer by making the act of volunteering arduous. Github is not the easiest thing to learn, so being able to help those who want to contribute and to respond to questions in a timely manner will be crucial to continuing lesson development. So far, we have AMAZING lesson materials in the LC repo - we want that excellence to continue, so properly supporting the maintainer role is key. 

Being able to support, through advice, information and materials, excellent workshops will be crucial towards making LC a go-to option for training. Having a clear statement of what an LC workshop is and what the requirements are, along with lists of local instructors is a must. All of this requires evaluating the SWC/DC model and using everything we can to foster the success of LC.

As far as the general vs. research librarian thing goes, I agree with Greg that we should start with an emphasis on research librarians, but there are a few lessons, especially the OR lesson, that are easily translated to use for a generalist. Metadata librarians especially loooooove OR, so if we get inquiries from non-research librarians, we can always point out those lessons that would fit their needs.

**Comment by drjwbaker** [comment] 2017-07-10 13:51
@pitviper6 Quick question: "Metadata librarians especially loooooove OR, so if we get inquiries from non-research librarians, we can always point out those lessons that would fit their needs". For me, if a metadata librarian works at a research or university library, they are in scope of what I think of a 'research librarians' (as opposed to public or school librarians)

Which is not to open a discussion, but rather given that we are international - as you point out - that we need to be careful to define terms.

**Comment by pitviper6** [comment] 2017-07-10 13:59
Ah, see I was thinking in terms of the workshop we held at UCSD, which was attended by many members of the Metadata Dept. While they did work in the library at a research-heavy university, they were very much a traditional cataloging department and didn't think of themselves in any way connected with research (or datasets). They saw OR as a tool that could help them with munging OCLC reports, reconciling linked data, etc.

**Comment by jezcope** [comment] 2017-07-10 15:27
👍 to @jt14den's point that

> "For example, there are many librarians with educational & assessment training and backgrounds who could help develop and improve the Carpentry-wide instructor training and assessment carpentry activities."

I think it's important to recognise that there's a synergy here and the LC community has a lot to offer the overall Carpentry community (which has already been well stated, but just to labour the point... 😁)

**Comment by richyvk** [comment] 2017-07-10 23:40
I'm finding myself wanting to ask: what, specifically, are the implications of merging with SC/DC? What would that **actually mean** in terms of fixing these issues, and placing restrictions on what we do(or not)?
If SC/DC is perceived as overly bureaucratic by some - then why? I think that needs to be explained/considered. Touching on this is Jez's point too - about LC having a voice in any merger. I don't buy, for example, LC being seen as "SWC/DC Essentials" - it shouldn't be so. We are, or should be, on the same level.

Is this really a case of us just not having a few simple processes in place to handle requests - for workshops, instructor training, or anything else? Clearly Belinda is feeling under pressure. Would some simple processes to handle these things, and assignment of responsibilities to handle this admin side of things,  make that go away a bit - without a full on merger at this point?

Take James point about not feeling obliged to answer all calls for workshops too, but I think we should be careful there. Personally, my view would be to accept as many as we can to keep the momentum going. Of course, without doing so much that the quality suffers etc.

**Comment by weaverbel** [comment] 2017-07-11 03:05
I agree @jezcope @jt14den especially where our lesson material has been updated more recently, e.g., we could contribute back the amazing work @ostephens and @ccronje et al have done on the LC OpenRefine lesson.

**Comment by chodacki** [comment] 2017-07-11 15:34
I agree with the sentiment above and believe that a merger is the best path forward for LC.  

I want to emphasize two points:
1. Quality. The success of LC is the the community AND in the quality of our efforts.  These efforts include the training...but also include processes for on boarding, new module development, and triaging workshop requests, etc.  I see a merger as helping us increase the quality (external perception and actual reality) of all of these efforts.  (I actually don't see how our quality of efforts is sustainable, otherwise).
2. Clarity of Roles.  The success of LC is that we have no formal organizational hierarchy...no single "leader" or "founder".  This has served us well because it has allowed for communities to grow where there is passion...in Australia, South Africa, US West Coast, UK, etc. but it has also created some confusion about roles.  We see that DC/SWC has a great mixture of local community passion and international coordination/facilitation.  We need more of this mixture in LC. 

Sounds exciting.  Count me in!

**Comment by weaverbel** [comment] 2017-07-11 23:59
I certainly want to credit @drjwbaker for having the initial idea and organising that first workshop. That sparked my interest, got me teaching it, and gave me the idea to organise the first sprint in 2016 to see who else out there might be interested in developing Library Carpentry. (I think we know the answer to that: a **LOT** of people).

Interest in Australia just exploded at that point, and I think the same is true for other countries who joined that sprint. The hard work of people like @ostephens, @jezcope, @ccronje, and @pitviper6 among many, many others (too many to name!) helped make what was a good idea a living, breathing, global community.

The power of an idea whose time has come ! 

Onwards and upwards.

**Comment by chodacki** [comment] 2017-07-12 00:06
I definitely think we all owe a ton to you @weaverbel. Without you, LC wouldn't be where it is today (or as well positioned for the future). 

And I should have added it above....but I am double excited that you are now at the Carpentries. That has really boosted my confidence that we can successfully navigate this transition. Go team!

**Comment by weaverbel** [comment] 2017-07-12 00:27
Aw, shucks @chodacki :-)

**Comment by drjwbaker** [comment] 2017-07-12 07:21
I love how this thread has turned into a love in :) I echo @chodacki: @weaverbel was the one who took my crazy idea and ran with it and proved to me that there are people in the world willing to do *good things* without being asked first. I'm also super happy that you are at the Carpentries Belinda. You've done us a **huge** strategic favour if/when we merge/integrate with Carpentries. But if you need to please please please do offload LC work where you can: I hate to think of people burying themselves for the cause.

**Comment by prcollingwood** [comment] 2017-07-13 02:39
I haven't been involved enough to be able to have an informed opinion on the questions Belinda is asking, but one thing that needs clarification is what distinguishes LC from other carpentries. Is the reason for aiming LC at research librarians to give them skills to teach researchers? If so, shouldn't they just do SWC instead? Or is LC to teach all librarians skills they can use to help them do their job more efficiently, which may or may not involve teaching those skills to researchers/students? I'd rather see it aimed at all librarians from the start keeping in mind that examples can be changed depending on the group.  Also we should recognise that what librarians do in their jobs can differ dramatically from country to country. What a research librarian in the USA does may be vastly different to what one does in Australia.

**Comment by drjwbaker** [comment] 2017-07-13 08:00
@prcollingwood Thanks for this. You've made two points here that I talk about so often that I feel like I'm becoming a broken record! These are:

> "Is the reason for aiming LC at research librarians to give them skills to teach researchers?"

Absolutely not. LC is about librarians and their daily practice.

> "What a research librarian in the USA does may be vastly different to what one does in Australia."

Absolutely agree. We must remain super mindful of this as we proceed.

**Comment by tracykteal** [comment] 2017-07-13 14:24
Thanks for this great discussion! SWC/DC are really excited about the idea of SWC/DC/LC and are fully supportive of a merger/integration. 

As many have already said it's a good opportunity for LC to connect with the existing scalable infrastructure, as well as a great synergy and LC and the LC community have a lot to contribute to the Carpentries. 

Also as @gvwilson says, with the SWC/DC merger it's good timing for LC to be involved in those discussion and process.

**Comment by pitviper6** [comment] 2017-07-13 20:25
@prcollingwood @drjwbaker 
I think of Library Carpentry as targeted towards any librarian who works with data, in any capacity. Hopefully (at least in my view) that will include librarians working with researchers and their data, but it could also be librarians in data-heavy roles, like metadata or acquisition librarians who would benefit from using OpenRefine or scripting to automate frequent tasks or create ongoing reports.

As for the international aspect of LC, I think that will be an organic part of the process along with deliberate outreach. Currently we have excellent and always-improving lessons for OR, bash/shell and git. How they are used, and the examples they work with will hopefully expand as instructors around the world develop new modules or examples for use in their particular circumstance, and contribute those back to the repository for others to use.

There seems to be a consensus that it would be good to at least actively explore the idea of becoming an official carpentry alongside SWC/DC.  @tracykteal, can you suggest a few practical ways LC can get in on the current SWC/DC discussions (particular calls, discussion forums, etc)?

**Comment by prcollingwood** [comment] 2017-07-13 22:08
Thanks @drjwbaker and @pitviper6 for your comments!

**Comment by weaverbel** [comment] 2017-07-13 22:36
I do agree with @drjwbaker on this, @prcollingwood 

> "Is the reason for aiming LC at research librarians to give them skills to teach researchers?"
> >  Absolutely not. LC is about librarians and their daily practice.

However, if librarians (having mastered them) felt able to teach/share those skills with researchers, then that would be a great outcome too.

**Comment by ndalyrose** [comment] 2017-08-02 09:40
Sorry I'm so late to respond but just to throw my two cents in that I wholeheartedly support a formal union with SWC/DC and am super excited by the prospect. I've been very, very keen to be more involved in LC, it has a wonderful symmetry with our existing training program at British Library (see: https://www.bl.uk/projects/digital-scholarship-training-programme) and I want to expose colleagues to it. However, I've found the ad hoc nature really hard to engage with meaningfully. Couldn't have said it better myself really, @weaverbel hits the nail on the head: 

> We need a structure and a system of governance that assigns responsibilities but that also opens up pathways for people to play a role. Ad hoc structures - what we have now - don't allow people to do that. They are actual barriers because no--one is sure who is authorised to do what or how they might take the initiative.

Next steps? Count me in!

**Comment by drjwbaker** [comment] 2017-08-04 15:28
Okay. Thank you all for your positive, informed, and substantive commentaries on what you want, how you feel, and where you want this to go.

Now is time to act. @weaverbel opened this issue 26 days ago. The SWC/DC merger is going ahead https://software-carpentry.org/blog/2017/06/merger.html (indeed, apace unless anything has changed!?). So if we want to merge with the merger and advocate for a voice/space/role for librarians in The Carpentries (and one that doesn't overload Belinda as the sole/primary voice), we need - as @ndalyrose indicates - some next steps.

It strikes me that these might include (in no particular order):

- Organise one or more calls (though, as I often say, we need to be clear on the specifics of **what** the call will be able). More than one due to our timezone troubles.
- Make it known to SWC/DC, in a formal venue that is minuted and stuff, of our intentions to join the merger, even if we are unclear what form that might take.
- Raise awareness of our intentions among the community who contribute to us and work with us.
- Find out what the SWC/DC merger means from a lesson signalling perspective (I hear from the above that 'Library' is a big draw for our community and so we'd want 'Library' to retain a place post-merger).
- Draw up an outline of an alternative plan of action should be decide to back away from a merger.
- Nominate individuals to take various parts of this work forward on behalf of LC and report back in a timely manner. Alternatively folks can put their hands up. As the one who started this thing I feel responsible to play take a lead here if I'm wanted (and feel free to tell me if I'm not)

**Comment by gvwilson** [comment] 2017-08-04 20:10
Thanks for the summary @drjwbaker - how about:

1. @weaverbel sets up a call with @tracykteal some time in the next two weeks in which people who've contributed to this thread can ask what the arrangements for group identity for SWC and DC will be post-merger, and whether the same arrangements will apply to LC.
2. If they'll have us, but some people are unhappy with the arrangements, those people have some time (two weeks?) to put together an alternative proposal (or multiple alternative proposals if they can't agree on what else to do).
3. We then hold a vote to choose among all proposals, with everyone who's contributed to a lesson and/or taught a workshop as the electorate.

The advantage of this path as I see it is that it won't leave us having said "no" to merger, and then not knowing what to do instead: people who don't want to merge will have to put forward a "what else" up front.

If SWC/DC say they don't want us (or don't want us now), then we repeat steps 2 and 3 without "merge" as an option, i.e., anyone who has a proposal can write it up for discussion over a fixed period (four weeks?) and then we'll put it to a vote.

**Comment by drjwbaker** [comment] 2017-08-04 20:53
I love that @gvwilson calls LC "us" :)

**Comment by drjwbaker** [comment] 2017-08-09 08:07
https://software-carpentry.org/blog/2017/08/mergermotions.html

**Comment by ljsmart** [comment] 2017-08-11 17:58
I support the merger and the process for garnering feedback.

I also appreciate the clarification of what LC is/is not. For whatever reason, it wasn't until I took instructor training that I internalized the distinction between librarians using the skills in their day-to-day vs. teaching librarians to teach the Carpentries. Our primary motivation for getting certified was to teach researchers on campus. I felt intimidated by SWC/DC even though I had a good baseline of technical skill and the "Library" in the title made it safer for me to check things out. I strongly believe that using the skills in our daily jobs would help librarians make the connection and inspire more librarians to do the outward facing workshops. I still don't see the distinctions as mutually exclusive. I'll be searching for more examples that non-metadata librarians can relate to when I do trainings.

**Comment by weaverbel** [comment] 2017-08-16 22:05
The consensus in the chatroom seems to be that we should schedule a couple of Library Carpentry community calls in a month or so to discuss the issues raised here and ways forward. I don't think there needs to be any kind of headlong rush for this so a month is fine. Data and Software Carpentry need to finalise their merger and then devise a process by which further Carpentries can potentially join that merged organisation. 

I am pretty sure there is no opportunity at this point for Library Carpentry to join the existing merger. That will need to conclude successfully before anything happens. Presumably the merged Carpentries will want a little time to bed down the merger on their side before thinking about another one ;-)

Once the dust has settled, we need to have our own house in order so that we can open discussions in a fruitful manner - i.e. we would need to know what we want to do, how, by when, etc and we would need a designated team of people to lead the discussions, negotiate terms, report back on progress etc.

**Comment by drjwbaker** [comment] 2017-08-29 07:20
@weaverbel As ever, thanks for being so sensible, articulate, and practical on this.

I'd be keen to get a call in the diary as soon as possible. First step is for people to indicate that they want to take part in such a call (note: timing is always tricky as we have to do some serious timezone juggling!).

Can I suggest that anyone who wants to join the call puts a thumbs up on https://github.com/data-lessons/librarycarpentry/issues/48#issuecomment-322118010 https://github.com/data-lessons/librarycarpentry/issues/48#issuecomment-322912945 and/or this comment (to recap, you can vote on this comment by adding a thumbs-up or thumbs-down emoji - just click the smiley face in the upper right.)

**Comment by weaverbel** [comment] 2017-09-01 01:36
@drjwbaker I will be pretty booked up 6-16 Sept with my US trip but am happy to do a call after that.

**Comment by drjwbaker** [comment] 2017-09-01 15:06
@weaverbel Okay.

**Comment by richyvk** [comment] 2017-09-04 10:52
@drjwbaker when we have the calls, can we tag on a 5 mins to talk about the website. Would like to get that finished off and launched if possible...

**Comment by drjwbaker** [comment] 2017-09-04 11:07
@richyvk 

I have the following people down for a call:
- @weaverbel 
- @richyvk 
- @tracykteal 
- @gvwilson 
- @ndalyrose 
- @jt14den 

Any other takers? We should start setting this up by the end of the week.

**Comment by pitviper6** [comment] 2017-09-04 12:14
I'd like to be on it! Thanks.

**Comment by tracykteal** [comment] 2017-09-04 18:59
LC’s growth has been awesome, and it sounds like there’s consensus that LC should be aligned with SWC & DC. Something that will help make this a clearer pathway is that SWC & DC have just passed their merger resolution!
Here’s the blog post: http://www.datacarpentry.org/blog/merger/

Software and Data Carpentry are moving towards being an umbrella organization that will support multiple types of curriculum. Draft areas of responsibility of the umbrella organization and the curriculum groups are outlined in this figure.

![swcdcmerger](https://user-images.githubusercontent.com/889238/30036369-8c23c1ac-9167-11e7-8e2e-d8a0bd7339e9.png)

Given all the discussion here, it makes sense to consider Library Carpentry the first ‘new’ Carpentry and to work together to outline what it means to be a ‘Name’ Carpentry. In the next few weeks we’ll be drafting a set of guidelines and getting that out for comment and discussion through [Requests for Comment](https://www.mediawiki.org/wiki/Requests_for_comment) or other methods.

So, I think the best thing to do in this discussion would be to **hold off a bit for that draft document** and then have the Library Carpentry community contribute to the discussions of a what a ‘Name’ Carpentry should be. The feedback of this group will be particularly important as you have experience with growing a curriculum and community and the challenges and opportunities, and you can identify what's essential to you.

One thing that will be important is having a group of about 5-7 people by around January who can act as an Advisory Committee. That doesn’t need to be the Advisory Committee forever, but is a group who can lead the communication and coordination at the beginning and has some time to commit to the activity.

A call would still be good for everyone to touch base, but maybe we could plan that for a few weeks out, and people could consider if they were interested in being on the Advisory Committee.

I'm really excited about this next step as a joint Carpentries' that can better support groups like Library Carpentry. Library Carpentry has been part of the motivation for a merger, and I appreciate you continuing to help lead the way.

**Comment by chodacki** [comment] 2017-09-04 19:43
Congratulations, Tracy! This is amazing news and I think the merger and upcoming clarity on expansion will help a lot as we move forward with LC. 

I agree that we should hold off a little bit on the next community meeting because there are a lot of moving parts. In addition to the changes you outlined, CDL has also recently received a grant to help fund future coordination of LC.  Among other things, it will fund two years for a coordinator position and is meant to serve the wider LC effort.  

I am very happy regarding the timing of this. It fulfills our earlier desires to bring resources to the table when we think of LC being part of the formal carpentry world. Glad this grant came to fruition right as the process for expansion is being determined. 

Maybe we can wait until the new merger guidance on how new Carpentries is drafted/circulated before we meet. That would give me time to finalize my grant paperwork and we could have a full picture of the resources we have...and still need...to make the merger successful in the new year.

**Comment by tracykteal** [comment] 2017-09-04 19:59
Congratulations on the grant! That's fantastic news and great timing! It does add in a positive way to the moving parts, so it sounds good to hold off on the community meeting until there's more information on the grant too.

**Comment by weaverbel** [comment] 2017-09-04 22:48
Amen to all that @tracykteal @chodacki @drjwbaker but equally we can have a call just to chat / catch up, especially about the website that @richyvk has done - we should finalise that. I am in the US 6-14 September so time zones might not be so nightmarish for a general call.

**Comment by richyvk** [comment] 2017-09-05 01:07
Thanks @drjwbaker. I'm happy to leave the website as is for now of course, just don't want it to stall. Happy to discuss whenever we schedule the big meeting. In the mean time I am going to make a concerted effort to get the Python lesson ready for test teaching :)

**Comment by weaverbel** [comment] 2017-09-05 01:48
I am going to raise an issue about the website redesign.

**Comment by drjwbaker** [comment] 2017-09-05 16:39
@tracykteal Shortly before you posted I saw the image you added above and the 'Lesson Organisations' and thought it looked a perfect place for LC. So in addition to my congrats of the continuing success of the merger, I'm delighted to see this 'Lesson Orgs' model emerge from the merger and look forward to seeing the draft doc on guidelines for 'Lesson Orgs'. I'm sure everyone involved in LC would be delighted if we could use our experience of rapid lesson development (still less than 2 years since I ran the first workshop!) using SWC/DC infrastructure to inform the process.

@chodacki If it is the one I'm thinking of, awesome. Super pleased this has happened. Is it official enough to announce and stuff? If so, it would be lovely if SWC/DC could host a part of the announcement.

@richyvk @weaverbel On the chat, I think a general catch up would be nice actually, especially given @richyvk's stellar work on the website. I'll move the discussion of the catchup to https://github.com/data-lessons/librarycarpentry/issues/49 for the sake of sanity!

**Comment by chodacki** [comment] 2017-09-06 01:37
@drjwbaker Regarding the grant...it has been awarded but I am still working out the specifics with my internal grants office. I will keep everyone posted when I have more clarity...and have something to communicate. Will make sure all of you and DC/SWC are part of that communication for sure.

**Comment by drjwbaker** [comment] 2017-09-06 07:58
@chodacki Okay. I look forward to hearing more when you and the funder are ready.

**Closed** 2018-06-01 14:34 UTC
